spring:
  rabbitmq:
    host: 192.168.1.32
    port: 5672
    username: guest
    password: guest
    listener:
      # 直连队列
      simple:
        acknowledge-mode: manual # 设置消费端手动 ack,默认是auto
        retry:
          enabled: true # 是否支持重试
      # 交换机
      direct:
        acknowledge-mode: manual # 设置消费端手动 ack,默认是auto
        retry:
          enabled: true # 是否支持重试