spring:
  rabbitmq:
    host: 192.168.1.32
    port: 5672
    username: guest
    password: guest
    publisher-returns: true # 确认消息已发送到队列(Queue)，发送者开启 confirm 确认机制，是否返回回调，默认值是false
    # 确认消息已发送到交换机(Exchange)，springboot.rabbitmq.publisher-confirm 新版本已被弃用，现在使用 spring.rabbitmq.publisher-confirm-type = correlated 实现相同效果
    #NONE值是禁用发布确认模式，是默认值
    #CORRELATED值是发布消息成功到交换器后会触发回调方法
    #SIMPLE值经测试有两种效果，其一效果和CORRELATED值一样会触发回调方法，其二在发布消息成功后使用rabbitTemplate调用waitForConfirms或waitForConfirmsOrDie方法等待broker节点返回发送结果，根据返回结果来判定下一步的逻辑，要注意的点是waitForConfirmsOrDie方法如果返回false则会关闭channel，则接下来无法发送消息到broker;
    publisher-confirm-type: correlated
    template:
      # 前提是publisher-returns需要先开启，此种方式在yml配置中定义spring.rabbit.template.mandatory=true 无效,必须在配置中rabbitTemplate.setMandatory(true);才生效
      mandatory: true #开启mandatory模式（开启失败回调）添加失败回调方法 rabbitTemplate.setReturnCallback();