spring:
  redis:
    database: 8
    host: 114.116.69.230
    port: 16379
    password:
    timeout: 120000
    lettuce:
      shutdown-timeout: 100ms # 关闭超时时间
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 200
        min-idle: 50
        time-between-eviction-runs: 60s